#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_DEVICE_INIT_NVIC_PRESENT
#define SL_CATALOG_EMLIB_CORE_DEBUG_CONFIG_PRESENT
#define SL_CATALOG_GLIB_PRESENT
#define SL_CATALOG_MEMLCD_USART_PRESENT
#define SL_CATALOG_KERNEL_PRESENT
#define SL_CATALOG_MICRIUMOS_KERNEL_PRESENT
#define SL_CATALOG_SYSTEMVIEW_TRACE_PRESENT
#define SL_CATALOG_LED0_PRESENT
#define SL_CATALOG_SIMPLE_LED_PRESENT
#define SL_CATALOG_SLEEPTIMER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
